packages:
  - internal/*
  - 'apps/*'
  - 'packages/*'
catalog:
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint/js': ^9.22.0
  '@types/eslint': ^9.6.1
  '@types/node': ^22.14.1
  '@typescript-eslint/parser': ^8.30.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  czg: ^1.11.1
  cz-git: ^1.11.1
  eslint: ^9.22.0
  eslint-plugin-jsdoc: ^50.6.9
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-import-x: ^4.10.5
  eslint-plugin-n: ^17.16.2
  eslint-plugin-perfectionist: ^4.12.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  lint-staged: ^15.5.1
  husky: ^9.1.7
  globals: ^16.0.0
  jsonc-eslint-parser: ^2.4.0
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.0.0
  react-dom: ^19.0.0
  turbo: ^2.5.0
  typescript: ^5.8.2
  typescript-eslint: ^8.26.1
  vite: ^6.3.1
  unbuild: ^3.5.0
