packages:
  - internal/*
  - 'apps/*'
  - 'packages/*'
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - 'scripts/*'
catalog:
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@eslint/js': ^9.22.0
  '@tailwindcss/vite': ^4.1.4
  '@types/eslint': ^9.6.1
  '@types/node': ^22.14.1
  '@typescript-eslint/parser': ^8.30.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  '@vitejs/plugin-react': '^4.3.4'
  cac: ^6.7.14
  chalk: ^5.4.1
  consola: ^3.4.0
  circular-dependency-scanner: ^2.3.0
  czg: ^1.11.1
  cz-git: ^1.11.1
  depcheck: ^1.4.7
  dayjs: ^1.11.13
  dotenv: ^16.4.7
  execa: ^9.5.2
  eslint: ^9.22.0
  eslint-plugin-jsdoc: ^50.6.9
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-import-x: ^4.10.5
  eslint-plugin-n: ^17.16.2
  eslint-plugin-perfectionist: ^4.12.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  lint-staged: ^15.5.1
  husky: ^9.1.7
  globals: ^16.0.0
  jsonc-eslint-parser: ^2.4.0
  publint: ^0.2.12
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.0.0
  react-dom: ^19.0.0
  rollup: ^4.40.0
  rollup-plugin-visualizer: ^5.14.0
  tailwindcss: ^4.0.0
  turbo: ^2.5.0
  typescript: ^5.8.2
  typescript-eslint: ^8.26.1
  vite: ^6.3.1
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-lazy-import: ^1.0.7
  unbuild: ^3.5.0
